#version 460

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 1, rgba8) uniform readonly  image2D accumImage;
layout(set = 0, binding = 2, rgba8) uniform writeonly image2D outImage;

void main() {
  ivec2 pix = ivec2(gl_GlobalInvocationID.xy);
  ivec2 dims = imageSize(outImage);
  if (pix.x >= dims.x || pix.y >= dims.y) return;
  vec4 c = imageLoad(accumImage, pix);
  imageStore(outImage, pix, c);
}
